### ISSUE TITLE
启动 ehforwarderbot 报错

### ISSUE THREAD

**Issue by FoKit** [Tedrolin/efb-wechat-pc-slave#1]
root@xiong:~# ehforwarderbot
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 330, in main
    conf = config.load_config()
  File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/config.py", line 41, in load_config
    raise ValueError(_("Master Channel is not specified in the profile config."))
ValueError: 未在配置档案中指定主端。

**Comment by Tedrolin** [comment]
如文字所见，本项目只是从端你还需要一个主段，请参阅 efb-telegram-master 的文档进行配置

**Comment by iTeraxo** [comment]
> 如文字所见，本项目只是从端你还需要一个主段，请参阅 efb-telegram-master 的文档进行配置



> root@xiong:~# ehforwarderbot Traceback (most recent call last): File "/usr/local/bin/ehforwarderbot", line 8, in sys.exit(main()) File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/**main**.py", line 330, in main conf = config.load_config() File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/config.py", line 41, in load_config raise ValueError(_("Master Channel is not specified in the profile config.")) ValueError: 未在配置档案中指定主端。



> root@xiong:~# ehforwarderbot Traceback (most recent call last): File "/usr/local/bin/ehforwarderbot", line 8, in sys.exit(main()) File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/**main**.py", line 330, in main conf = config.load_config() File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/config.py", line 41, in load_config raise ValueError(_("Master Channel is not specified in the profile config.")) ValueError: 未在配置档案中指定主端。

> root@xiong:~# ehforwarderbot Traceback (most recent call last): File "/usr/local/bin/ehforwarderbot", line 8, in sys.exit(main()) File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/**main**.py", line 330, in main conf = config.load_config() File "/usr/local/python3/lib/python3.8/site-packages/ehforwarderbot/config.py", line 41, in load_config raise ValueError(_("Master Channel is not specified in the profile config.")) ValueError: 未在配置档案中指定主端。

老哥解决了吗？我也遇到了，能跟我说下吗
