### ISSUE TITLE
遇见的问题

### ISSUE THREAD

**Issue by 0honus0** [Tedrolin/efb-wechat-pc-slave#4]
@消息发送tg端无@

**Comment by 0honus0** [comment]
添加好友后昵称显示为 wxid

**Comment by moosetk** [comment]
'''
uri:   # ws path to wechat pc 
APP_ID:   # Optional, app id corresponds to the one configured on wechathook
APP_KEY:
'''
这些东西要在哪里获得呢？
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5678)

**Comment by 0honus0** [comment]
> ''' uri: # ws path to wechat pc APP_ID: # Optional, app id corresponds to the one configured on wechathook APP_KEY: ''' 这些东西要在哪里获得呢？ raise OSError(err, f'Connect call failed {address}') ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5678)

自己看下文档吧
https://telegra.ph/docker-wechatPc--ehForwarderBot-Full-Tutorial-03-26

**Comment by moosetk** [comment]
感谢
